# Site settings
title: Blogging on NLP, DL and more...
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Thoughts on understanding technologies. Starting with basics like word2vec to 
 more advanced topics like LLMs, KG and Embedding Models. The goal is to explain
 each of these topics in a more intuitive manner. This is also a note to self 
 kind of blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rnr415.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  rnr415

# Build settings
#permalink: /:year/:title:output_ext
markdown: kramdown
theme: minima # Use Minima, or another theme.  See available themes below.
#plugins:
#  - jekyll-feed # optional, creates an RSS feed
#exclude:
#  - Gemfile
#  - Gemfile.lock
